### ISSUE TITLE
Look at the Word document with the description of which inputs need to manipulated for the Upper Yaquina DO model in the Rbranch

### ISSUE THREAD

**Issue by dsobota** [dsobota/Upper_Yaquina_PEST#2]
Look in the Rbranch for the word document.

**Comment by kbrannan** [comment]
Does it need to be a word doc? If not, try to keep everything in the repo plain text

**Comment by kbrannan** [comment]
when you want to put the link to an entire file, use the url in the browser
https://github.com/dsobota/Upper_Yaquina_PEST/blob/Rbranch/Map%20of%20Input%20data%20to%20be%20manipulated%20for%20QUAL2Kw.docx

**Comment by dsobota** [comment]
https://github.com/dsobota/Upper_Yaquina_PEST/blob/Rbranch/Map_inputs_Q2K.txt

Here is the text file of the Q2K inputs
