### ISSUE TITLE
Example of the ins.txt file

### ISSUE THREAD

**Issue by kbrannan** [dsobota/Upper_Yaquina_PEST#3]
Below is an example of the ins.txt file the the python script uses to read the qual2kw output file. You can change this ins.txt file to acess your output for the pareto analysis

https://github.com/dsobota/Upper_Yaquina_PEST/blob/3e33b21f6610a220025e46657584bd58d9132ccd/python/model_ins.txt#L1

**Comment by dsobota** [comment]
Is this the same file that I will need to modify for accessing model inputs to Q2K?

**Comment by kbrannan** [comment]
Yes, I suggest cloning this branch, then create a new local branch that you will make changes in. Then modify the model_ins.txt so it only reads the data you are interested in. Finally, push your branch to GitHub and create an issue for me to review. If this makes sense to you, close this issue and proceed.

**Comment by dsobota** [comment]
Will do

**Comment by dsobota** [comment]
Reworked the ins file to read Q2K outputs and focus on all forms of nutrients and hourly dissolved oxygen from midnight to 6 AM in all reaches
