### ISSUE TITLE
Look at model input text file

### ISSUE THREAD

**Issue by dsobota** [dsobota/Upper_Yaquina_PEST#4]
Please take a look at the modified model_ins.txt file in the new branch here:

https://github.com/dsobota/Upper_Yaquina_PEST/blob/pymethod_Upper_Yaquina/python/model_ins.txt

Parameters are defined here:

https://github.com/dsobota/Upper_Yaquina_PEST/blob/pymethod_Upper_Yaquina/python/model_ins_definitions.txt

**Comment by kbrannan** [comment]
Looks good. I will send an issue to you for the next step
